//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36373
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.36373.
// 
#pragma warning disable 1591

namespace GenerateGLFromCRM.ScvBridgeApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BridgeAPISoap", Namespace="http://www.bicinfor.com/")]
    public partial class BridgeAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListCarsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListCitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListCostCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadTicketInXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteTicketInXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListTicketFeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListTicketFeesInXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnfilledTicketsInXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnsubmitedTicketsInXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetFeeExtractedOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetFillProcessedOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSubmitProcessedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BridgeAPI() {
            this.Url = global::GenerateGLFromCRM.Properties.Settings.Default.AutoIssueAndShip_ScvBridgeApi_BridgeAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event ListCarsCompletedEventHandler ListCarsCompleted;
        
        /// <remarks/>
        public event ListCitiesCompletedEventHandler ListCitiesCompleted;
        
        /// <remarks/>
        public event ListCostCategoriesCompletedEventHandler ListCostCategoriesCompleted;
        
        /// <remarks/>
        public event ListUsersCompletedEventHandler ListUsersCompleted;
        
        /// <remarks/>
        public event ReadTicketCompletedEventHandler ReadTicketCompleted;
        
        /// <remarks/>
        public event ReadTicketInXmlCompletedEventHandler ReadTicketInXmlCompleted;
        
        /// <remarks/>
        public event WriteTicketCompletedEventHandler WriteTicketCompleted;
        
        /// <remarks/>
        public event WriteTicketInXmlCompletedEventHandler WriteTicketInXmlCompleted;
        
        /// <remarks/>
        public event UpdateTicketCompletedEventHandler UpdateTicketCompleted;
        
        /// <remarks/>
        public event DeleteTicketCompletedEventHandler DeleteTicketCompleted;
        
        /// <remarks/>
        public event ListTicketFeesCompletedEventHandler ListTicketFeesCompleted;
        
        /// <remarks/>
        public event ListTicketFeesInXmlCompletedEventHandler ListTicketFeesInXmlCompleted;
        
        /// <remarks/>
        public event GetUnfilledTicketsInXmlCompletedEventHandler GetUnfilledTicketsInXmlCompleted;
        
        /// <remarks/>
        public event GetUnsubmitedTicketsInXmlCompletedEventHandler GetUnsubmitedTicketsInXmlCompleted;
        
        /// <remarks/>
        public event SetFeeExtractedCompletedEventHandler SetFeeExtractedCompleted;
        
        /// <remarks/>
        public event SetFillProcessedCompletedEventHandler SetFillProcessedCompleted;
        
        /// <remarks/>
        public event SetSubmitProcessedCompletedEventHandler SetSubmitProcessedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/Test", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test(string message) {
            object[] results = this.Invoke("Test", new object[] {
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync(string message) {
            this.TestAsync(message, null);
        }
        
        /// <remarks/>
        public void TestAsync(string message, object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[] {
                        message}, this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/ListCars", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OCar[] ListCars() {
            object[] results = this.Invoke("ListCars", new object[0]);
            return ((OCar[])(results[0]));
        }
        
        /// <remarks/>
        public void ListCarsAsync() {
            this.ListCarsAsync(null);
        }
        
        /// <remarks/>
        public void ListCarsAsync(object userState) {
            if ((this.ListCarsOperationCompleted == null)) {
                this.ListCarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListCarsOperationCompleted);
            }
            this.InvokeAsync("ListCars", new object[0], this.ListCarsOperationCompleted, userState);
        }
        
        private void OnListCarsOperationCompleted(object arg) {
            if ((this.ListCarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListCarsCompleted(this, new ListCarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/ListCities", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OCity[] ListCities() {
            object[] results = this.Invoke("ListCities", new object[0]);
            return ((OCity[])(results[0]));
        }
        
        /// <remarks/>
        public void ListCitiesAsync() {
            this.ListCitiesAsync(null);
        }
        
        /// <remarks/>
        public void ListCitiesAsync(object userState) {
            if ((this.ListCitiesOperationCompleted == null)) {
                this.ListCitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListCitiesOperationCompleted);
            }
            this.InvokeAsync("ListCities", new object[0], this.ListCitiesOperationCompleted, userState);
        }
        
        private void OnListCitiesOperationCompleted(object arg) {
            if ((this.ListCitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListCitiesCompleted(this, new ListCitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/ListCostCategories", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OCostCategory[] ListCostCategories() {
            object[] results = this.Invoke("ListCostCategories", new object[0]);
            return ((OCostCategory[])(results[0]));
        }
        
        /// <remarks/>
        public void ListCostCategoriesAsync() {
            this.ListCostCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void ListCostCategoriesAsync(object userState) {
            if ((this.ListCostCategoriesOperationCompleted == null)) {
                this.ListCostCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListCostCategoriesOperationCompleted);
            }
            this.InvokeAsync("ListCostCategories", new object[0], this.ListCostCategoriesOperationCompleted, userState);
        }
        
        private void OnListCostCategoriesOperationCompleted(object arg) {
            if ((this.ListCostCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListCostCategoriesCompleted(this, new ListCostCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/ListUsers", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OUser[] ListUsers() {
            object[] results = this.Invoke("ListUsers", new object[0]);
            return ((OUser[])(results[0]));
        }
        
        /// <remarks/>
        public void ListUsersAsync() {
            this.ListUsersAsync(null);
        }
        
        /// <remarks/>
        public void ListUsersAsync(object userState) {
            if ((this.ListUsersOperationCompleted == null)) {
                this.ListUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListUsersOperationCompleted);
            }
            this.InvokeAsync("ListUsers", new object[0], this.ListUsersOperationCompleted, userState);
        }
        
        private void OnListUsersOperationCompleted(object arg) {
            if ((this.ListUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListUsersCompleted(this, new ListUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/ReadTicket", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OTicket ReadTicket(string ticketObjectID) {
            object[] results = this.Invoke("ReadTicket", new object[] {
                        ticketObjectID});
            return ((OTicket)(results[0]));
        }
        
        /// <remarks/>
        public void ReadTicketAsync(string ticketObjectID) {
            this.ReadTicketAsync(ticketObjectID, null);
        }
        
        /// <remarks/>
        public void ReadTicketAsync(string ticketObjectID, object userState) {
            if ((this.ReadTicketOperationCompleted == null)) {
                this.ReadTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadTicketOperationCompleted);
            }
            this.InvokeAsync("ReadTicket", new object[] {
                        ticketObjectID}, this.ReadTicketOperationCompleted, userState);
        }
        
        private void OnReadTicketOperationCompleted(object arg) {
            if ((this.ReadTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadTicketCompleted(this, new ReadTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/ReadTicketInXml", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReadTicketInXml(string ticketObjectID) {
            object[] results = this.Invoke("ReadTicketInXml", new object[] {
                        ticketObjectID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReadTicketInXmlAsync(string ticketObjectID) {
            this.ReadTicketInXmlAsync(ticketObjectID, null);
        }
        
        /// <remarks/>
        public void ReadTicketInXmlAsync(string ticketObjectID, object userState) {
            if ((this.ReadTicketInXmlOperationCompleted == null)) {
                this.ReadTicketInXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadTicketInXmlOperationCompleted);
            }
            this.InvokeAsync("ReadTicketInXml", new object[] {
                        ticketObjectID}, this.ReadTicketInXmlOperationCompleted, userState);
        }
        
        private void OnReadTicketInXmlOperationCompleted(object arg) {
            if ((this.ReadTicketInXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadTicketInXmlCompleted(this, new ReadTicketInXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/WriteTicket", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WriteTicket(OTicket ticket) {
            object[] results = this.Invoke("WriteTicket", new object[] {
                        ticket});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WriteTicketAsync(OTicket ticket) {
            this.WriteTicketAsync(ticket, null);
        }
        
        /// <remarks/>
        public void WriteTicketAsync(OTicket ticket, object userState) {
            if ((this.WriteTicketOperationCompleted == null)) {
                this.WriteTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteTicketOperationCompleted);
            }
            this.InvokeAsync("WriteTicket", new object[] {
                        ticket}, this.WriteTicketOperationCompleted, userState);
        }
        
        private void OnWriteTicketOperationCompleted(object arg) {
            if ((this.WriteTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteTicketCompleted(this, new WriteTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/WriteTicketInXml", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WriteTicketInXml(string ticketInXML) {
            object[] results = this.Invoke("WriteTicketInXml", new object[] {
                        ticketInXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WriteTicketInXmlAsync(string ticketInXML) {
            this.WriteTicketInXmlAsync(ticketInXML, null);
        }
        
        /// <remarks/>
        public void WriteTicketInXmlAsync(string ticketInXML, object userState) {
            if ((this.WriteTicketInXmlOperationCompleted == null)) {
                this.WriteTicketInXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteTicketInXmlOperationCompleted);
            }
            this.InvokeAsync("WriteTicketInXml", new object[] {
                        ticketInXML}, this.WriteTicketInXmlOperationCompleted, userState);
        }
        
        private void OnWriteTicketInXmlOperationCompleted(object arg) {
            if ((this.WriteTicketInXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteTicketInXmlCompleted(this, new WriteTicketInXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/UpdateTicket", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateTicket(OTicket ticket) {
            object[] results = this.Invoke("UpdateTicket", new object[] {
                        ticket});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTicketAsync(OTicket ticket) {
            this.UpdateTicketAsync(ticket, null);
        }
        
        /// <remarks/>
        public void UpdateTicketAsync(OTicket ticket, object userState) {
            if ((this.UpdateTicketOperationCompleted == null)) {
                this.UpdateTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTicketOperationCompleted);
            }
            this.InvokeAsync("UpdateTicket", new object[] {
                        ticket}, this.UpdateTicketOperationCompleted, userState);
        }
        
        private void OnUpdateTicketOperationCompleted(object arg) {
            if ((this.UpdateTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTicketCompleted(this, new UpdateTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/DeleteTicket", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteTicket(string ticketObjectID) {
            object[] results = this.Invoke("DeleteTicket", new object[] {
                        ticketObjectID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteTicketAsync(string ticketObjectID) {
            this.DeleteTicketAsync(ticketObjectID, null);
        }
        
        /// <remarks/>
        public void DeleteTicketAsync(string ticketObjectID, object userState) {
            if ((this.DeleteTicketOperationCompleted == null)) {
                this.DeleteTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteTicketOperationCompleted);
            }
            this.InvokeAsync("DeleteTicket", new object[] {
                        ticketObjectID}, this.DeleteTicketOperationCompleted, userState);
        }
        
        private void OnDeleteTicketOperationCompleted(object arg) {
            if ((this.DeleteTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteTicketCompleted(this, new DeleteTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/ListTicketFees", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OTicketFees[] ListTicketFees(string fromPlace) {
            object[] results = this.Invoke("ListTicketFees", new object[] {
                        fromPlace});
            return ((OTicketFees[])(results[0]));
        }
        
        /// <remarks/>
        public void ListTicketFeesAsync(string fromPlace) {
            this.ListTicketFeesAsync(fromPlace, null);
        }
        
        /// <remarks/>
        public void ListTicketFeesAsync(string fromPlace, object userState) {
            if ((this.ListTicketFeesOperationCompleted == null)) {
                this.ListTicketFeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListTicketFeesOperationCompleted);
            }
            this.InvokeAsync("ListTicketFees", new object[] {
                        fromPlace}, this.ListTicketFeesOperationCompleted, userState);
        }
        
        private void OnListTicketFeesOperationCompleted(object arg) {
            if ((this.ListTicketFeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListTicketFeesCompleted(this, new ListTicketFeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/ListTicketFeesInXml", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListTicketFeesInXml(string fromPlace) {
            object[] results = this.Invoke("ListTicketFeesInXml", new object[] {
                        fromPlace});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListTicketFeesInXmlAsync(string fromPlace) {
            this.ListTicketFeesInXmlAsync(fromPlace, null);
        }
        
        /// <remarks/>
        public void ListTicketFeesInXmlAsync(string fromPlace, object userState) {
            if ((this.ListTicketFeesInXmlOperationCompleted == null)) {
                this.ListTicketFeesInXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListTicketFeesInXmlOperationCompleted);
            }
            this.InvokeAsync("ListTicketFeesInXml", new object[] {
                        fromPlace}, this.ListTicketFeesInXmlOperationCompleted, userState);
        }
        
        private void OnListTicketFeesInXmlOperationCompleted(object arg) {
            if ((this.ListTicketFeesInXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListTicketFeesInXmlCompleted(this, new ListTicketFeesInXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/GetUnfilledTicketsInXml", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUnfilledTicketsInXml() {
            object[] results = this.Invoke("GetUnfilledTicketsInXml", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUnfilledTicketsInXmlAsync() {
            this.GetUnfilledTicketsInXmlAsync(null);
        }
        
        /// <remarks/>
        public void GetUnfilledTicketsInXmlAsync(object userState) {
            if ((this.GetUnfilledTicketsInXmlOperationCompleted == null)) {
                this.GetUnfilledTicketsInXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnfilledTicketsInXmlOperationCompleted);
            }
            this.InvokeAsync("GetUnfilledTicketsInXml", new object[0], this.GetUnfilledTicketsInXmlOperationCompleted, userState);
        }
        
        private void OnGetUnfilledTicketsInXmlOperationCompleted(object arg) {
            if ((this.GetUnfilledTicketsInXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnfilledTicketsInXmlCompleted(this, new GetUnfilledTicketsInXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/GetUnsubmitedTicketsInXml", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUnsubmitedTicketsInXml() {
            object[] results = this.Invoke("GetUnsubmitedTicketsInXml", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUnsubmitedTicketsInXmlAsync() {
            this.GetUnsubmitedTicketsInXmlAsync(null);
        }
        
        /// <remarks/>
        public void GetUnsubmitedTicketsInXmlAsync(object userState) {
            if ((this.GetUnsubmitedTicketsInXmlOperationCompleted == null)) {
                this.GetUnsubmitedTicketsInXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnsubmitedTicketsInXmlOperationCompleted);
            }
            this.InvokeAsync("GetUnsubmitedTicketsInXml", new object[0], this.GetUnsubmitedTicketsInXmlOperationCompleted, userState);
        }
        
        private void OnGetUnsubmitedTicketsInXmlOperationCompleted(object arg) {
            if ((this.GetUnsubmitedTicketsInXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnsubmitedTicketsInXmlCompleted(this, new GetUnsubmitedTicketsInXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/SetFeeExtracted", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetFeeExtracted(string erpTicketID) {
            object[] results = this.Invoke("SetFeeExtracted", new object[] {
                        erpTicketID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetFeeExtractedAsync(string erpTicketID) {
            this.SetFeeExtractedAsync(erpTicketID, null);
        }
        
        /// <remarks/>
        public void SetFeeExtractedAsync(string erpTicketID, object userState) {
            if ((this.SetFeeExtractedOperationCompleted == null)) {
                this.SetFeeExtractedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetFeeExtractedOperationCompleted);
            }
            this.InvokeAsync("SetFeeExtracted", new object[] {
                        erpTicketID}, this.SetFeeExtractedOperationCompleted, userState);
        }
        
        private void OnSetFeeExtractedOperationCompleted(object arg) {
            if ((this.SetFeeExtractedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetFeeExtractedCompleted(this, new SetFeeExtractedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/SetFillProcessed", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetFillProcessed(string erpTicketID) {
            object[] results = this.Invoke("SetFillProcessed", new object[] {
                        erpTicketID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetFillProcessedAsync(string erpTicketID) {
            this.SetFillProcessedAsync(erpTicketID, null);
        }
        
        /// <remarks/>
        public void SetFillProcessedAsync(string erpTicketID, object userState) {
            if ((this.SetFillProcessedOperationCompleted == null)) {
                this.SetFillProcessedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetFillProcessedOperationCompleted);
            }
            this.InvokeAsync("SetFillProcessed", new object[] {
                        erpTicketID}, this.SetFillProcessedOperationCompleted, userState);
        }
        
        private void OnSetFillProcessedOperationCompleted(object arg) {
            if ((this.SetFillProcessedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetFillProcessedCompleted(this, new SetFillProcessedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bicinfor.com/SetSubmitProcessed", RequestNamespace="http://www.bicinfor.com/", ResponseNamespace="http://www.bicinfor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetSubmitProcessed(string erpTicketID) {
            object[] results = this.Invoke("SetSubmitProcessed", new object[] {
                        erpTicketID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetSubmitProcessedAsync(string erpTicketID) {
            this.SetSubmitProcessedAsync(erpTicketID, null);
        }
        
        /// <remarks/>
        public void SetSubmitProcessedAsync(string erpTicketID, object userState) {
            if ((this.SetSubmitProcessedOperationCompleted == null)) {
                this.SetSubmitProcessedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSubmitProcessedOperationCompleted);
            }
            this.InvokeAsync("SetSubmitProcessed", new object[] {
                        erpTicketID}, this.SetSubmitProcessedOperationCompleted, userState);
        }
        
        private void OnSetSubmitProcessedOperationCompleted(object arg) {
            if ((this.SetSubmitProcessedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSubmitProcessedCompleted(this, new SetSubmitProcessedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bicinfor.com/")]
    public partial class OCar {
        
        private string objectIDField;
        
        private string licensePlateField;
        
        private string cityField;
        
        private System.DateTime createTimeField;
        
        private string createUserIDField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string LicensePlate {
            get {
                return this.licensePlateField;
            }
            set {
                this.licensePlateField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bicinfor.com/")]
    public partial class OFeeItem {
        
        private string categoryField;
        
        private string priceField;
        
        private string remarkField;
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bicinfor.com/")]
    public partial class OTicketFees {
        
        private string erpTicketIDField;
        
        private string ticketObjectIDField;
        
        private string stateField;
        
        private string driver1Field;
        
        private string driver2Field;
        
        private string car1Field;
        
        private string car2Field;
        
        private string productNameField;
        
        private System.DateTime createAtField;
        
        private string roadCostsField;
        
        private OFeeItem[] feeItemsField;
        
        /// <remarks/>
        public string ErpTicketID {
            get {
                return this.erpTicketIDField;
            }
            set {
                this.erpTicketIDField = value;
            }
        }
        
        /// <remarks/>
        public string TicketObjectID {
            get {
                return this.ticketObjectIDField;
            }
            set {
                this.ticketObjectIDField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Driver1 {
            get {
                return this.driver1Field;
            }
            set {
                this.driver1Field = value;
            }
        }
        
        /// <remarks/>
        public string Driver2 {
            get {
                return this.driver2Field;
            }
            set {
                this.driver2Field = value;
            }
        }
        
        /// <remarks/>
        public string Car1 {
            get {
                return this.car1Field;
            }
            set {
                this.car1Field = value;
            }
        }
        
        /// <remarks/>
        public string Car2 {
            get {
                return this.car2Field;
            }
            set {
                this.car2Field = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateAt {
            get {
                return this.createAtField;
            }
            set {
                this.createAtField = value;
            }
        }
        
        /// <remarks/>
        public string RoadCosts {
            get {
                return this.roadCostsField;
            }
            set {
                this.roadCostsField = value;
            }
        }
        
        /// <remarks/>
        public OFeeItem[] FeeItems {
            get {
                return this.feeItemsField;
            }
            set {
                this.feeItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bicinfor.com/")]
    public partial class OCustomer {
        
        private string objectIDField;
        
        private string nameField;
        
        private string receiptAmountField;
        
        private string toDateField;
        
        private string toMilageField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptAmount {
            get {
                return this.receiptAmountField;
            }
            set {
                this.receiptAmountField = value;
            }
        }
        
        /// <remarks/>
        public string ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        public string ToMilage {
            get {
                return this.toMilageField;
            }
            set {
                this.toMilageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bicinfor.com/")]
    public partial class OTicket {
        
        private string objectIDField;
        
        private string driver1Field;
        
        private string driver2Field;
        
        private string fromPlaceField;
        
        private string car1Field;
        
        private string car2Field;
        
        private string productNameField;
        
        private string goodsPlaceField;
        
        private string routeField;
        
        private string adminRemarkField;
        
        private System.DateTime startFuelFillingTimeField;
        
        private System.DateTime endFuelFillingTimeField;
        
        private System.DateTime fromTimeField;
        
        private System.DateTime returnTimeField;
        
        private string createUserField;
        
        private string usernameField;
        
        private System.DateTime createAtField;
        
        private string serialDayField;
        
        private int serialNoField;
        
        private int previewCountField;
        
        private int printCountField;
        
        private string stateField;
        
        private string[] roadCostsField;
        
        private OCustomer[] customersField;
        
        private string netWeightField;
        
        private string oilAmountField;
        
        private string produceRemarkField;
        
        private string replacementAmountField;
        
        private string replacementTimeField;
        
        private string roughWeightField;
        
        private string tareWeightField;
        
        private string driverRemarkField;
        
        private string emptyPoundAmountField;
        
        private string formMilageField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string Driver1 {
            get {
                return this.driver1Field;
            }
            set {
                this.driver1Field = value;
            }
        }
        
        /// <remarks/>
        public string Driver2 {
            get {
                return this.driver2Field;
            }
            set {
                this.driver2Field = value;
            }
        }
        
        /// <remarks/>
        public string FromPlace {
            get {
                return this.fromPlaceField;
            }
            set {
                this.fromPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string Car1 {
            get {
                return this.car1Field;
            }
            set {
                this.car1Field = value;
            }
        }
        
        /// <remarks/>
        public string Car2 {
            get {
                return this.car2Field;
            }
            set {
                this.car2Field = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public string GoodsPlace {
            get {
                return this.goodsPlaceField;
            }
            set {
                this.goodsPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string Route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
            }
        }
        
        /// <remarks/>
        public string AdminRemark {
            get {
                return this.adminRemarkField;
            }
            set {
                this.adminRemarkField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartFuelFillingTime {
            get {
                return this.startFuelFillingTimeField;
            }
            set {
                this.startFuelFillingTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndFuelFillingTime {
            get {
                return this.endFuelFillingTimeField;
            }
            set {
                this.endFuelFillingTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FromTime {
            get {
                return this.fromTimeField;
            }
            set {
                this.fromTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReturnTime {
            get {
                return this.returnTimeField;
            }
            set {
                this.returnTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateAt {
            get {
                return this.createAtField;
            }
            set {
                this.createAtField = value;
            }
        }
        
        /// <remarks/>
        public string SerialDay {
            get {
                return this.serialDayField;
            }
            set {
                this.serialDayField = value;
            }
        }
        
        /// <remarks/>
        public int SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        public int PreviewCount {
            get {
                return this.previewCountField;
            }
            set {
                this.previewCountField = value;
            }
        }
        
        /// <remarks/>
        public int PrintCount {
            get {
                return this.printCountField;
            }
            set {
                this.printCountField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string[] RoadCosts {
            get {
                return this.roadCostsField;
            }
            set {
                this.roadCostsField = value;
            }
        }
        
        /// <remarks/>
        public OCustomer[] Customers {
            get {
                return this.customersField;
            }
            set {
                this.customersField = value;
            }
        }
        
        /// <remarks/>
        public string NetWeight {
            get {
                return this.netWeightField;
            }
            set {
                this.netWeightField = value;
            }
        }
        
        /// <remarks/>
        public string OilAmount {
            get {
                return this.oilAmountField;
            }
            set {
                this.oilAmountField = value;
            }
        }
        
        /// <remarks/>
        public string ProduceRemark {
            get {
                return this.produceRemarkField;
            }
            set {
                this.produceRemarkField = value;
            }
        }
        
        /// <remarks/>
        public string ReplacementAmount {
            get {
                return this.replacementAmountField;
            }
            set {
                this.replacementAmountField = value;
            }
        }
        
        /// <remarks/>
        public string ReplacementTime {
            get {
                return this.replacementTimeField;
            }
            set {
                this.replacementTimeField = value;
            }
        }
        
        /// <remarks/>
        public string RoughWeight {
            get {
                return this.roughWeightField;
            }
            set {
                this.roughWeightField = value;
            }
        }
        
        /// <remarks/>
        public string TareWeight {
            get {
                return this.tareWeightField;
            }
            set {
                this.tareWeightField = value;
            }
        }
        
        /// <remarks/>
        public string DriverRemark {
            get {
                return this.driverRemarkField;
            }
            set {
                this.driverRemarkField = value;
            }
        }
        
        /// <remarks/>
        public string EmptyPoundAmount {
            get {
                return this.emptyPoundAmountField;
            }
            set {
                this.emptyPoundAmountField = value;
            }
        }
        
        /// <remarks/>
        public string FormMilage {
            get {
                return this.formMilageField;
            }
            set {
                this.formMilageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bicinfor.com/")]
    public partial class OUser {
        
        private string objectIDField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string telephoneField;
        
        private string cityField;
        
        private System.DateTime createTimeField;
        
        private string stateField;
        
        private string roleField;
        
        private string tokenField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bicinfor.com/")]
    public partial class OCostCategory {
        
        private string objectIDField;
        
        private string nameField;
        
        private System.DateTime createTimeField;
        
        private string createUserIDField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bicinfor.com/")]
    public partial class OCity {
        
        private string objectIDField;
        
        private string fullnameField;
        
        private string addressField;
        
        private string cityField;
        
        private string nameField;
        
        private string telephoneField;
        
        private System.DateTime createTimeField;
        
        private string createUserIDField;
        
        /// <remarks/>
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public string Fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void ListCarsCompletedEventHandler(object sender, ListCarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListCarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListCarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OCar[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OCar[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void ListCitiesCompletedEventHandler(object sender, ListCitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OCity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OCity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void ListCostCategoriesCompletedEventHandler(object sender, ListCostCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListCostCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListCostCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OCostCategory[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OCostCategory[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void ListUsersCompletedEventHandler(object sender, ListUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OUser[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OUser[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void ReadTicketCompletedEventHandler(object sender, ReadTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OTicket Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OTicket)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void ReadTicketInXmlCompletedEventHandler(object sender, ReadTicketInXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadTicketInXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadTicketInXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void WriteTicketCompletedEventHandler(object sender, WriteTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void WriteTicketInXmlCompletedEventHandler(object sender, WriteTicketInXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteTicketInXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteTicketInXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void UpdateTicketCompletedEventHandler(object sender, UpdateTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void DeleteTicketCompletedEventHandler(object sender, DeleteTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void ListTicketFeesCompletedEventHandler(object sender, ListTicketFeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListTicketFeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListTicketFeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OTicketFees[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OTicketFees[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void ListTicketFeesInXmlCompletedEventHandler(object sender, ListTicketFeesInXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListTicketFeesInXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListTicketFeesInXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void GetUnfilledTicketsInXmlCompletedEventHandler(object sender, GetUnfilledTicketsInXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnfilledTicketsInXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnfilledTicketsInXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void GetUnsubmitedTicketsInXmlCompletedEventHandler(object sender, GetUnsubmitedTicketsInXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnsubmitedTicketsInXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnsubmitedTicketsInXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void SetFeeExtractedCompletedEventHandler(object sender, SetFeeExtractedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetFeeExtractedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetFeeExtractedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void SetFillProcessedCompletedEventHandler(object sender, SetFillProcessedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetFillProcessedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetFillProcessedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    public delegate void SetSubmitProcessedCompletedEventHandler(object sender, SetSubmitProcessedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36373")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSubmitProcessedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSubmitProcessedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591